services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: projecttravel
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql



  spring-boot-app:
    container_name: springbootapp
    build: ./
    restart: always
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - JWTSECRET=${JWTSECRET}
      - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "8080:8080"

volumes:
  mysql-data:
